name: Publish FRP Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 25 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest FRP version
        id: frp-version
        run: |
          version=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | grep -oP '"tag_name": "v\K.*?(?=")')
          echo "frp_version=$version" >> $GITHUB_OUTPUT

      - name: Build and push FRP image (with frps.toml support)
        uses: docker/build-push-action@v4
        with:
          context: ./frp
          file: ./frp/Dockerfile
          push: true
          tags: kjlion/frp:alpine
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            FRP_VERSION=${{ steps.frp-version.outputs.frp_version }}
